;; keys
(bind-keys
 ("C-x C-j" . execute-extended-command)
 ("C-s"     . isearch-forward-regexp)
 ("C-r"     . isearch-backward-regexp)
 ("C-M-s"   . isearch-forward)
 ("C-M-r"   . isearch-backward)
 ("C-x C-g" . keyboard-quit)
 ("C-c C-g" . keyboard-quit)
 ("C-c C-c" . keyboard-quit)
 ("C-;"     . other-window)
 ("C-<end>" . other-window)
 ("<f36>" . other-window)
 ("C-M-;"   . other-frame)
 ("C-z"     . nil)
 ("C-x a r" . align-regexp)
 ("C-x a a" . align)
 ;; ("C-c h" .   'my/copy-whole-buffer)
 ("C-c s"   . my/swap-windows)
 ([remap dabbrev-expand] . hippie-expand)
 ("C-x RET RET" . compile)
 ("C-c C-o" . ff-find-other-file)
 ;; ([remap list-buffers] . ibuffer-list-buffers)
 )

(provide 'key-config)
